---
- name: install NGINX Server.
  apt: pkg=nginx state=installed update-cache=yes

- name: copy base nginx configuration.
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: delete default vhost.
  action: file path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx

- name: ensure nginx is running
  service: name=nginx state=started
